# This is a generated file. Not intended for manual editing.
services:
  simpleapp:
    build:
      context: "C:\\Users\\admin\\RiderProjects\\SimpleApp\\SimpleApp"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "simpleapp:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "C:\\Users\\admin\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\admin\\RiderProjects\\SimpleApp\\SimpleApp:/app:rw"
    - "C:\\Users\\admin\\RiderProjects\\SimpleApp:/src:rw"
    - "C:\\Users\\admin\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.1.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\admin\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_6_27_09_27_39:/var/opt/rider-debugger:rw"
    working_dir: "/app"
